# Generated by Django 2.2.4 on 2020-12-19 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('connections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='graph_app.Person')),
            ],
        ),
    ]
