# Generated by Django 2.2.4 on 2020-12-20 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='connections',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='graph_app.Person'),
        ),
    ]
